/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "secondary-container": "#464557",
        "on-secondary-fixed": "#1a1a2a",
        "on-surface": "#dee4de",
        "on-primary-fixed": "#002115",
        "error-container": "#93000a",
        "on-background": "#dee4de",
        "inverse-surface": "#dee4de",
        "surface": "#0f1512",
        "on-secondary-container": "#b5b3c8",
        "primary-fixed-dim": "#62dcad",
        "primary": "#aaffd8",
        "on-tertiary-fixed-variant": "#643f05",
        "surface-container": "#1b211e",
        "on-tertiary": "#472a00",
        "on-secondary": "#2f2f40",
        "tertiary-container": "#ffc783",
        "inverse-on-surface": "#2b322e",
        "surface-bright": "#343b37",
        "on-tertiary-fixed": "#2a1700",
        "tertiary-fixed-dim": "#f3bc79",
        "secondary": "#c6c4da",
        "on-error-container": "#ffdad6",
        "primary-fixed": "#80f9c8",
        "surface-container-lowest": "#090f0c",
        "primary-container": "#6ee7b7",
        "surface-dim": "#0f1512",
        "background": "#0f1512",
        "surface-container-low": "#171d1a",
        "on-primary": "#003827",
        "on-tertiary-container": "#795118",
        "surface-container-high": "#252b28",
        "on-error": "#690005",
        "inverse-primary": "#006c4e",
        "secondary-fixed-dim": "#c6c4da",
        "on-primary-container": "#006649",
        "outline": "#86948c",
        "on-primary-fixed-variant": "#00513a",
        "surface-variant": "#303632",
        "on-secondary-fixed-variant": "#464557",
        "error": "#ffb4ab",
        "tertiary-fixed": "#ffddb7",
        "surface-container-highest": "#303632",
        "surface-tint": "#62dcad",
        "tertiary": "#ffead5",
        "outline-variant": "#3d4a43",
        "secondary-fixed": "#e3e0f7",
        "on-surface-variant": "#bccac1",
      },
      borderRadius: {
        DEFAULT: "0.25rem",
        lg: "0.5rem",
        xl: "0.75rem",
        full: "9999px",
      },
      spacing: {
        "gutter": "24px",
        "section-gap": "120px",
        "container-max": "1280px",
        "margin-mobile": "16px",
        "base": "8px",
      },
      fontFamily: {
        "headline-lg": ["Space Grotesk", "sans-serif"],
        "headline-md": ["Space Grotesk", "sans-serif"],
        "headline-lg-mobile": ["Space Grotesk", "sans-serif"],
        "body-lg": ["Inter", "sans-serif"],
        "label-mono": ["JetBrains Mono", "monospace"],
        "label-caps": ["JetBrains Mono", "monospace"],
        "display-xl": ["Space Grotesk", "sans-serif"],
        "body-md": ["Inter", "sans-serif"],
      },
      fontSize: {
        "headline-lg": ["48px", { lineHeight: "1.1", letterSpacing: "-0.03em", fontWeight: "700" }],
        "headline-md": ["24px", { lineHeight: "1.2", letterSpacing: "-0.02em", fontWeight: "600" }],
        "headline-lg-mobile": ["32px", { lineHeight: "1.1", letterSpacing: "-0.03em", fontWeight: "700" }],
        "body-lg": ["18px", { lineHeight: "1.6", letterSpacing: "0em", fontWeight: "400" }],
        "label-mono": ["14px", { lineHeight: "1.4", letterSpacing: "0.05em", fontWeight: "500" }],
        "label-caps": ["12px", { lineHeight: "1.2", letterSpacing: "0.1em", fontWeight: "700" }],
        "display-xl": ["72px", { lineHeight: "1.0", letterSpacing: "-0.03em", fontWeight: "700" }],
        "body-md": ["16px", { lineHeight: "1.6", letterSpacing: "0em", fontWeight: "400" }],
      },
    },
  },
  plugins: [],
}
